apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-service
  labels:
    app: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: 108101918154.dkr.ecr.us-east-1.amazonaws.com/flag-service:v1.0.0-43b92f7
          ports:
            - containerPort: 8002
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.auth-service.svc.cluster.local:8001"
          envFrom:
            - secretRef:
                name: flag-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 20
